/**
 * Nutrition evidence ingest contracts — backend-side types for
 * barcode confirmation, AI photo proposals, and source-state-aware
 * nutrition ingestion.
 *
 * Non-negotiable: unconfirmed proposals never enter normalized nutrition.
 * Only confirmed or user-edited evidence can affect totals.
 */

export type NutritionSourceState = 'live' | 'manual' | 'estimated' | 'mixed';

export type NutritionEvidenceIngestSource =
  | 'manual'
  | 'barcode_confirmed'
  | 'barcode_unconfirmed'
  | 'ai_photo_confirmed'
  | 'ai_photo_proposed'
  | 'ai_photo_edited'
  | 'ai_photo_rejected'
  | 'cronometer';

export type PhotoProposalStatus =
  | 'proposed'
  | 'user_confirmed'
  | 'user_edited'
  | 'rejected';

/** Barcode lookup confidence — how trustworthy the database entry is. */
export type BarcodeLookupConfidence = 'high' | 'medium' | 'low' | null;

/** Barcode data quality signals. */
export type BarcodeConflictStatus =
  | 'none'              // Single match, no conflicts
  | 'multiple_entries'  // Multiple DB entries for same barcode
  | 'incomplete_data'   // Entry exists but missing key fields
  | 'regional_mismatch' // Product exists but may differ by region
  | 'user_reported';    // Community-flagged data quality issue

/** Barcode scan candidate — may or may not have macros from OpenFoodFacts. */
export interface BarcodeScanCandidate {
  barcode: string;
  /** Product name from lookup, null if lookup failed. */
  productName: string | null;
  /** Brand from lookup. */
  brand: string | null;
  /** Serving size from lookup. */
  servingSize: string | null;
  /** Whether OpenFoodFacts returned data. */
  lookupAvailable: boolean;
  /** Proposed macros from lookup. Null if lookup unavailable. */
  proposedCalories: number | null;
  proposedProteinG: number | null;
  proposedCarbG: number | null;
  proposedFatG: number | null;
  proposedFibreG: number | null;
  /** Confidence in the lookup data. */
  confidence: BarcodeLookupConfidence;
  /** Data quality/conflict status. */
  conflictStatus: BarcodeConflictStatus;
  /** Which fields are missing from the database entry. */
  missingFields: string[];
  /** Product region/country codes from the database. */
  regionCodes: string[];
  /** Open Food Facts completeness score (0-100), null if unavailable. */
  completenessScore: number | null;
  /** Whether macros were user-edited (vs raw from DB). */
  userEdited: boolean;
}

/** Confirmed barcode entry — user has verified/edited the macros. */
export interface BarcodeConfirmedEntry {
  barcode: string;
  productName: string | null;
  servingGrams: number;
  /** Final confirmed macros (user may have edited). */
  calories: number | null;
  proteinG: number | null;
  carbG: number | null;
  fatG: number | null;
  fibreG: number | null;
  /** How confident: high if from OpenFoodFacts, medium if user-edited. */
  confidence: 'high' | 'medium' | 'low';
}

/** AI meal photo proposal — generated by AI, awaiting user confirmation. */
export interface AiPhotoProposal {
  /** Unique proposal ID. */
  proposalId: string;
  /** URI or reference to the photo. */
  photoRef: string;
  /** AI's description of what it saw. */
  description: string;
  /** Proposed macros. */
  proposedCalories: number | null;
  proposedProteinG: number | null;
  proposedCarbG: number | null;
  proposedFatG: number | null;
  /** Confidence in the estimate. */
  confidence: 'high' | 'medium' | 'low';
  /** What the AI couldn't determine. */
  missingFields: string[];
  /** Current proposal status. */
  status: PhotoProposalStatus;
}

/** Confirmed/edited photo entry — user has accepted or edited the AI estimate. */
export interface AiPhotoConfirmedEntry {
  proposalId: string;
  photoRef: string;
  description: string;
  /** Final macros (may differ from proposal if user edited). */
  calories: number | null;
  proteinG: number | null;
  carbG: number | null;
  fatG: number | null;
  /** How it was confirmed. */
  confirmationMethod: 'user_confirmed' | 'user_edited';
  /** Original confidence from AI (preserved for audit). */
  originalConfidence: 'high' | 'medium' | 'low';
  /** What was still missing after confirmation. */
  missingFields: string[];
}

/**
 * Extended nutrition ingest payload — accepts source state and
 * evidence provenance. Backward-compatible with existing payload.
 */
export interface NutritionIngestPayloadV2 {
  date: string;
  source: 'cronometer' | 'manual' | 'barcode' | 'ai_photo' | 'mixed';
  /** Source state: live (Cronometer API), manual, estimated (AI photo), mixed. */
  sourceState: NutritionSourceState;
  /** Whether this entry has been confirmed by the user. */
  confirmed: boolean;
  /** Total macros (only populated when confirmed). */
  calories_kcal: number | null;
  protein_g: number | null;
  carbs_g: number | null;
  fat_g: number | null;
  fibre_g: number | null;
  sugar_g: number | null;
  sodium_mg: number | null;
  water_ml: number | null;
  updated_at?: string | null;
  /** Which fields are missing. */
  missingFields: string[];
  /** Evidence items that contributed (for audit). */
  evidenceIds: string[];
  /** Source dependencies for provenance tracking. */
  sourceDependencies: string[];
}

/**
 * Check whether a nutrition ingest payload should be allowed
 * to enter normalized nutrition. Only confirmed entries pass.
 */
export function isNutritionIngestAllowed(payload: NutritionIngestPayloadV2): boolean {
  return payload.confirmed === true;
}

/**
 * Derive nutrition coverage from a V2 payload.
 */
export function deriveNutritionCoverage(
  payload: NutritionIngestPayloadV2,
): 'full' | 'partial' | 'none' {
  const count = [
    payload.calories_kcal,
    payload.protein_g,
    payload.carbs_g,
    payload.fat_g,
  ].filter((v) => v != null).length;
  return count === 4 ? 'full' : count > 0 ? 'partial' : 'none';
}
