#!/usr/bin/expect -f
set timeout 15
spawn ssh -o StrictHostKeyChecking=no linux@100.101.39.98
expect "*?assword:*"
send "goldfighting1\r"
expect "*?linux@*"
send "sudo bash -c 'echo -e \"\\\[global\\\]\\nmap to guest = Bad User\\n\\\[nas\\\]\\npath = /data\\nbrowseable = yes\\nread only = no\\nguest ok = yes\\nforce user = root\" > /Volumes/Lauburu-Monorepo/smb_pool_config.conf'\r"
expect "*?linux@*"
send "cd ~/nas_samba && sudo docker-compose restart samba_nas_gateway\r"
expect "*?linux@*"
send "exit\r"
