#!/usr/bin/expect -f
set timeout 15

spawn ssh -o StrictHostKeyChecking=no -o PubkeyAuthentication=no aaronmaher@100.103.212.21
expect "assword:"
send "goldfighting1\r"
expect "\\$"
send "echo 'goldfighting1' | sudo -S mkdir -p /Volumes/NAS && echo 'goldfighting1' | sudo -S mount -t nfs -o vers=4,resvport 100.101.39.98:/ /Volumes/NAS\r"
expect "\\$"
send "cat /Volumes/NAS/PROOF_OF_SWARM.md\r"
expect "\\$"
send "exit\r"
