import type { KnowledgeDocument } from '../types';

export const referenceCoachedLandingDoc: KnowledgeDocument = {
  id: 'kb-reference-coached-landing-workflow',
  version: 1,
  canonicalSlug: 'reference-coached-landing-workflow',
  title: 'Reference coached landing workflow',
  documentType: 'workflow',
  category: 'app_feature_behavior',
  subcategories: ['route_focus'],
  summary:
    'Home can send a coached recommendation into Reference via focus params, and Reference consumes those params to expand and highlight the recommended technique.',
  detailedBody: [
    'Verified workflow from current repo:',
    '- Home navigates to `/reference` with focus params including `focus`, `focusRole`, `focusHeading`, `focusTechnique`, `focusReason`, and `focusNonce`.',
    '- Reference reads those params through `useLocalSearchParams` and uses them to focus the relevant position/technique.',
    '- `focusNonce` exists to force repeated navigation to the same focus target to re-trigger.',
    '',
    'This is implemented today.',
  ].join('\n'),
  keyPoints: [
    'Home navigates to /reference with focus params for coached recommendations',
    'Reference uses useLocalSearchParams to consume focus params',
    'focusNonce forces repeated navigation to same target to re-trigger',
  ],
  sourceOrigin: 'repo_code',
  sourceAuthority: 'repo_verified',
  evidenceBucket: 'app_context',
  retrievalTags: ['reference', 'focus', 'routing', 'coaching'],
  relatedFeatures: ['reference_focus', 'coaching_recommendation'],
  applicableSurfaces: ['home', 'reference'],
  truthStatus: 'implemented_truth',
  confidence: 'high',
  confidenceNotes: 'Verified from repo code inspection',
  evidenceStrength: 'not_applicable',
  implementationStatus: 'live_verified',
  openQuestions: [
    'route-param names should stay aligned between Home and Reference or the workflow breaks',
  ],
  doNotOverclaim: [],
  status: 'active',
  reviewOwner: 'mobile-engineering',
  reviewCadenceDays: 21,
  lastReviewed: '2026-04-12',
  createdAt: '2026-04-12',
  updatedAt: '2026-04-12',
  vectorId: null,
  relatedEntities: ['focusNonce', 'useLocalSearchParams', 'reference'],
  supersedes: [],
};
