"""
Canonical Port Backend Package
Version: 3.0.0-CANONICAL

Unified backend system integrating all 12 Lauburu Spec Modules,
central state management, FastAPI routing, and TUI bridge services.
"""

from .models import (
    GlobalBackendSummary,
    MeshNodeState,
    ModuleActionRequest,
    ModuleActionResponse,
    ModuleCategory,
    ModuleHealthStatus,
    SpecModuleHealthCheckResult,
    SpecModuleMetadata,
    SpecModuleStatus,
    SpecModuleTelemetry,
    TelemetryFieldSchema,
    TelemetrySchemaDefinition,
    current_utc_time,
)
from .base_module import BaseSpecModule
from .state import BackendStateStore, get_backend_state, reset_backend_state
from .router import create_app_router, app_router
from .app import create_app, app
from .spec_modules import (
    Spec00CoreInfraModule,
    Spec01AppsEcosystemModule,
    Spec02AiInferenceModule,
    Spec03BiometricsDspModule,
    Spec04DataMemoryModule,
    Spec05AgentsSwarmsModule,
    Spec06ScriptsToolingModule,
    Spec07DocsArchitectureModule,
    Spec08BusinessCommerceModule,
    Spec09AppStoreProductionModule,
    Spec10SpatialGrapplingModule,
    Spec11SecurityModule,
    Spec12ContinuousLoraModule,
    Spec1112SecurityLoraModule,
    CANONICAL_SPEC_MODULE_CLASSES,
    create_all_spec_modules,
    create_spec_module_map,
)
from .training_telemetry_collector import (
    MPSCRingBuffer,
    TrainingTelemetryCollector,
    training_telemetry_collector,
    get_ingestion_loop_telemetry,
    get_gatekeeper_telemetry,
    get_hf_epoch_vram_gate,
    get_red_blue_arena_telemetry,
    get_mesh_healing_telemetry,
    get_stealth_compute_telemetry,
    get_software_dev_game_telemetry,
    get_spatial_grappling_telemetry,
    get_all_gyms_telemetry,
    calculate_kinematic_torque,
)

__all__ = [
    "BaseSpecModule",
    "BackendStateStore",
    "get_backend_state",
    "reset_backend_state",
    "create_app_router",
    "app_router",
    "create_app",
    "app",
    "GlobalBackendSummary",
    "MeshNodeState",
    "ModuleActionRequest",
    "ModuleActionResponse",
    "ModuleCategory",
    "ModuleHealthStatus",
    "SpecModuleHealthCheckResult",
    "SpecModuleMetadata",
    "SpecModuleStatus",
    "SpecModuleTelemetry",
    "TelemetryFieldSchema",
    "TelemetrySchemaDefinition",
    "current_utc_time",
    "Spec00CoreInfraModule",
    "Spec01AppsEcosystemModule",
    "Spec02AiInferenceModule",
    "Spec03BiometricsDspModule",
    "Spec04DataMemoryModule",
    "Spec05AgentsSwarmsModule",
    "Spec06ScriptsToolingModule",
    "Spec07DocsArchitectureModule",
    "Spec08BusinessCommerceModule",
    "Spec09AppStoreProductionModule",
    "Spec10SpatialGrapplingModule",
    "Spec11SecurityModule",
    "Spec12ContinuousLoraModule",
    "Spec1112SecurityLoraModule",
    "CANONICAL_SPEC_MODULE_CLASSES",
    "create_all_spec_modules",
    "create_spec_module_map",
    "MPSCRingBuffer",
    "TrainingTelemetryCollector",
    "training_telemetry_collector",
    "get_ingestion_loop_telemetry",
    "get_gatekeeper_telemetry",
    "get_hf_epoch_vram_gate",
    "get_red_blue_arena_telemetry",
    "get_mesh_healing_telemetry",
    "get_stealth_compute_telemetry",
    "get_software_dev_game_telemetry",
    "get_spatial_grappling_telemetry",
    "get_all_gyms_telemetry",
    "calculate_kinematic_torque",
]
